### ISSUE TITLE
No window opens 

### ISSUE THREAD

**Issue by spicybeef003** [TimothyMeadows/GUvrs#2]
Thanks for making this app. I tried to use it on Windows 11 (.NET framework v.6.0.11) but when i open the .exe file no window pops up. I tried on Windows 10 too but no dice. Any thoughts on things I could try?

**Comment by TimothyMeadows** [comment]
Some users have reported that they needed to use the exact version of .NET provided in the error message when the application opens. If your not even seeing this. You might try opening a command prompt, or power shell window, and then dragging the application into that window and running it there. It should output an error if it's not able to execute on your system for whatever reason (version, or permission problems).

Please comment to reopen if you still can't find a solution.
