### ISSUE TITLE
Auto-open does not automatically open a new window on Mac (Arm 64)

### ISSUE THREAD

**Issue by dan-marius** [TimothyMeadows/GUvrs#27]
Compiled with Visual Studio Code on a Macbook M1, the Auto-open function does not work. Will investigate.

**Comment by TimothyMeadows** [comment]
This might be system related as the same can happen on windows if no default browser is configured in windows.

**Comment by dan-marius** [comment]
Possible but function "OnIDClick" works just fine if I click on the ID. Somehow it does not work if called from the "OnBegin" function if checking for the toogle.

**Comment by TimothyMeadows** [comment]
Got it, that's not the case then as both would not work then. Interesting, will look into this when time permits hopefully in the next few days. If you find anything else out let me know!

**Comment by TimothyMeadows** [comment]
This should now be resolved in 3.0.0 (seems to be working ok on mine) please re-open if issues still exists.
